version: "3.8"
services:
  opendata:
    container_name: opendata
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "4001:4001" # ipfs swarm
      - "4001:4001/udp"

    volumes:
      - ./ipfs/ipfs0:/data/ipfs
