version: "3.8"
services:
  opendata_ipfs_node:
    image: sethealth/opendata-ipfs-node
    ports:
      - "4001:4001" # ipfs swarm
      - "4001:4001/udp"

    volumes:
      - ./ipfs/ipfs0:/data/ipfs
