version: "3.8"
services:
  opendata_ipfs:
    image: ipfs/go-ipfs:v0.9.1
    sysctls:
      net.core.rmem_max: 2500000

    environment:
      IPFS_PATH: /data/ipfs
      IPFS_PROFILE: server,flatfs

    ports:
      - "4001:4001" # ipfs swarm
      - "4001:4001/udp"

    volumes:
      - ./ipfs/ipfs0:/data/ipfs

  opendata_sentinel:
    image: sethealth/opendata-sentinel
    environment:
      IPFS_URL: opendata_ipfs:5001
      PINSET_URL: https://api.set.health/pinset/openview-health/bu-5643105772503040
      OPENDATA_NODE: sethealth_do
    depends_on:
      - opendata_ipfs
