version: "3.8"
services:
  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:latest
    environment:
      IPFS_PROFILE: server,badgerds
      #   "PeerID": "12D3KooWNjUoWoxiAP1KQBEXtb7caChGac6hMbVxzm1QgxLymTh6",

    ports:
      - "4001:4001" # ipfs swarm
      - "4001:4001/udp"

    volumes:
      - ./ipfs/ipfs0:/data/ipfs

  cluster0:
    container_name: cluster0
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs0
    environment:
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API

    volumes:
      - ./ipfs/cluster0:/data/ipfs-cluster

  api:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile

    depends_on:
      - cluster0

    environment:
      CLUSTER_HOST: cluster0
      PORT: 5000

    ports:
      - "5000:5000"
